CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	NickName VARCHAR(50) NOT NULL UNIQUE,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Pwd VARCHAR(100) NOT NULL,
	Birthdate DATE NOT NULL,
	Salt VARCHAR(150) NOT NULL,
	IsActive TINYINT DEFAULT 1 NOT NULL,
	Birthdate date  NOT NULL,
	Salt VARCHAR(150) NOT NULL,
	IsActive TINYINT NOT NULL  DEFAULT 1,
	[IdRole] INT NOT NULL REFERENCES [Roles](Id),
	
)
