CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	NickName VARCHAR(50) NOT NULL UNIQUE,
	Email VARCHAR(50) NOT NULL UNIQUE,
	Pwd VARCHAR(100) NOT NULL,
	Birthdate date  NOT NULL,
	Salt VARCHAR(100) NOT NULL,
	IsActive TINYINT NOT NULL  DEFAULT 1,
	[IdRole] INT NOT NULL REFERENCES [Roles](Id),
    CONSTRAINT CHK_Birthdate CHECK ((YEAR(getDate()) -Year(Birthdate) ) >= 18)
	
)
